import { LiveEditorState, EditorPage } from '../types/liveEditor';

export function getDefaultEditorState(): LiveEditorState {
  return {
    currentPage: "home",
    selectedSection: null,
    texts: {
      // Navbar
      'navbar-brand': {
        id: 'navbar-brand',
        value: 'Ataraxia',
        defaultValue: 'Ataraxia',
        page: 'shared',
        section: 'navbar',
        label: 'Brand Name',
        type: 'heading',
        fontSizeMin: 16,
        fontSizeMax: 32,
      },
      'navbar-book-call': {
        id: 'navbar-book-call',
        value: 'Book a Call',
        defaultValue: 'Book a Call',
        page: 'shared',
        section: 'navbar',
        label: 'Book a Call Button',
        type: 'button',
        fontSizeMin: 14,
        fontSizeMax: 18,
      },
      'navbar-home': {
        id: 'navbar-home',
        value: 'Home',
        defaultValue: 'Home',
        page: 'shared',
        section: 'navbar',
        label: 'Home Link',
        type: 'link',
        fontSizeMin: 14,
        fontSizeMax: 18,
      },
      'navbar-about': {
        id: 'navbar-about',
        value: 'About',
        defaultValue: 'About',
        page: 'shared',
        section: 'navbar',
        label: 'About Link',
        type: 'link',
        fontSizeMin: 14,
        fontSizeMax: 18,
      },
      'navbar-services': {
        id: 'navbar-services',
        value: 'Services',
        defaultValue: 'Services',
        page: 'shared',
        section: 'navbar',
        label: 'Services Link',
        type: 'link',
        fontSizeMin: 14,
        fontSizeMax: 18,
      },
      'navbar-workshops': {
        id: 'navbar-workshops',
        value: 'Workshop',
        defaultValue: 'Workshop',
        page: 'shared',
        section: 'navbar',
        label: 'Workshops Link',
        type: 'link',
        fontSizeMin: 14,
        fontSizeMax: 18,
      },
      'navbar-journals': {
        id: 'navbar-journals',
        value: 'Journals',
        defaultValue: 'Journals',
        page: 'shared',
        section: 'navbar',
        label: 'Journals Link',
        type: 'link',
        fontSizeMin: 14,
        fontSizeMax: 18,
      },
      'navbar-blog': {
        id: 'navbar-blog',
        value: 'Blog',
        defaultValue: 'Blog',
        page: 'shared',
        section: 'navbar',
        label: 'Blog Link',
        type: 'link',
        fontSizeMin: 14,
        fontSizeMax: 18,
      },
      'navbar-contact': {
        id: 'navbar-contact',
        value: 'Contact',
        defaultValue: 'Contact',
        page: 'shared',
        section: 'navbar',
        label: 'Contact Link',
        type: 'link',
        fontSizeMin: 14,
        fontSizeMax: 18,
      },
      // Footer
      'footer-brand': {
        id: 'footer-brand',
        value: 'Ataraxia',
        defaultValue: 'Ataraxia',
        page: 'shared',
        section: 'footer',
        label: 'Brand Name',
        type: 'heading',
        fontSizeMin: 16,
        fontSizeMax: 32,
      },
      'footer-tagline': {
        id: 'footer-tagline',
        value: 'Tranquillity in Transformation',
        defaultValue: 'Tranquillity in Transformation',
        page: 'shared',
        section: 'footer',
        label: 'Tagline',
        type: 'paragraph',
        fontSizeMin: 14,
        fontSizeMax: 18,
      },
      'footer-copyright': {
        id: 'footer-copyright',
        value: '© 2025 Ataraxia by Aqsa Khan. All rights reserved.',
        defaultValue: '© 2025 Ataraxia by Aqsa Khan. All rights reserved.',
        page: 'shared',
        section: 'footer',
        label: 'Copyright',
        type: 'label',
        fontSizeMin: 12,
        fontSizeMax: 16,
      },
      // Home Page - Hero
      'home-hero-section-label': {
        id: 'home-hero-section-label',
        value: 'ATARAXIA — MOVEMENT EDITION',
        defaultValue: 'ATARAXIA — MOVEMENT EDITION',
        page: 'home',
        section: 'hero',
        label: 'Section Label',
        type: 'label',
        fontSizeMin: 12,
        fontSizeMax: 16,
      },
      'home-hero-headline-1': {
        id: 'home-hero-headline-1',
        value: 'You Were Not Born Blocked.',
        defaultValue: 'You Were Not Born Blocked.',
        page: 'home',
        section: 'hero',
        label: 'Hero Headline Line 1',
        type: 'heading',
        fontSizeMin: 28,
        fontSizeMax: 72,
      },
      'home-hero-headline-2': {
        id: 'home-hero-headline-2',
        value: 'You Were Built That Way.',
        defaultValue: 'You Were Built That Way.',
        page: 'home',
        section: 'hero',
        label: 'Hero Headline Line 2',
        type: 'heading',
        fontSizeMin: 28,
        fontSizeMax: 72,
      },
      'home-hero-subtitle': {
        id: 'home-hero-subtitle',
        value: 'And what was built — can be rebuilt.',
        defaultValue: 'And what was built — can be rebuilt.',
        page: 'home',
        section: 'hero',
        label: 'Hero Subtitle',
        type: 'subheading',
        fontSizeMin: 16,
        fontSizeMax: 24,
      },
      'home-hero-description': {
        id: 'home-hero-description',
        value: 'The mind does not hold pain the way we hold a memory. It holds it in the body, in the breath, in the patterns that repeat without invitation. In the version of yourself that keeps almost arriving.\n\nAtaraxia exists for the moment you decide that almost is no longer enough.\n\nThis is the 4X System — a proprietary methodology integrating the deepest tools of subconscious transformation into one coherent, precision framework. Not a programme. Not a practice. A complete architecture for who you are becoming.',
        defaultValue: 'The mind does not hold pain the way we hold a memory. It holds it in the body, in the breath, in the patterns that repeat without invitation. In the version of yourself that keeps almost arriving.\n\nAtaraxia exists for the moment you decide that almost is no longer enough.\n\nThis is the 4X System — a proprietary methodology integrating the deepest tools of subconscious transformation into one coherent, precision framework. Not a programme. Not a practice. A complete architecture for who you are becoming.',
        page: 'home',
        section: 'hero',
        label: 'Hero Description',
        type: 'paragraph',
        fontSizeMin: 14,
        fontSizeMax: 18,
      },
      'home-hero-cta-1': {
        id: 'home-hero-cta-1',
        value: '▶  Begin Your 4X Reset',
        defaultValue: '▶  Begin Your 4X Reset',
        page: 'home',
        section: 'hero',
        label: 'CTA Button 1',
        type: 'button',
        fontSizeMin: 14,
        fontSizeMax: 18,
      },
      'home-hero-cta-2': {
        id: 'home-hero-cta-2',
        value: '▶  Apply for 1:1 Intensive',
        defaultValue: '▶  Apply for 1:1 Intensive',
        page: 'home',
        section: 'hero',
        label: 'CTA Button 2',
        type: 'button',
        fontSizeMin: 14,
        fontSizeMax: 18,
      },
      'home-hero-cta-3': {
        id: 'home-hero-cta-3',
        value: '▶  Explore The System',
        defaultValue: '▶  Explore The System',
        page: 'home',
        section: 'hero',
        label: 'CTA Button 3',
        type: 'button',
        fontSizeMin: 14,
        fontSizeMax: 18,
      },
      // Home Page - 4X Framework
      'home-4x-section-label': {
        id: 'home-4x-section-label',
        value: 'THE 4X FRAMEWORK — VISUAL ELEMENT',
        defaultValue: 'THE 4X FRAMEWORK — VISUAL ELEMENT',
        page: 'home',
        section: '4x-framework',
        label: 'Section Label',
        type: 'label',
        fontSizeMin: 12,
        fontSizeMax: 16,
      },
      'home-4x-heading': {
        id: 'home-4x-heading',
        value: 'The System. In Four Movements.',
        defaultValue: 'The System. In Four Movements.',
        page: 'home',
        section: '4x-framework',
        label: '4X Heading',
        type: 'heading',
        fontSizeMin: 24,
        fontSizeMax: 48,
      },
      'home-4x-description': {
        id: 'home-4x-description',
        value: 'Each stage is a complete world of work. Each one prepares the ground for the next. Together, they form the only kind of transformation that is permanent — because it changes not what you do, but who you are at the level where decisions are actually made.',
        defaultValue: 'Each stage is a complete world of work. Each one prepares the ground for the next. Together, they form the only kind of transformation that is permanent — because it changes not what you do, but who you are at the level where decisions are actually made.',
        page: 'home',
        section: '4x-framework',
        label: '4X Description',
        type: 'paragraph',
        fontSizeMin: 14,
        fontSizeMax: 18,
      },
      // Home Page - Why Stuck
      'home-stuck-section-label': {
        id: 'home-stuck-section-label',
        value: 'WHY PEOPLE STAY STUCK',
        defaultValue: 'WHY PEOPLE STAY STUCK',
        page: 'home',
        section: 'why-stuck',
        label: 'Section Label',
        type: 'label',
        fontSizeMin: 12,
        fontSizeMax: 16,
      },
      'home-stuck-heading': {
        id: 'home-stuck-heading',
        value: 'The Invisible Architecture of Staying Small',
        defaultValue: 'The Invisible Architecture of Staying Small',
        page: 'home',
        section: 'why-stuck',
        label: 'Heading',
        type: 'heading',
        fontSizeMin: 24,
        fontSizeMax: 48,
      },
      'home-stuck-description': {
        id: 'home-stuck-description',
        value: 'Most people who feel limited are not lacking ambition, intelligence, or effort. They are operating against an invisible internal structure — subconscious conditioning, unresolved emotional memory, and an identity that was shaped in the absence of real tools.\n\nThe body carries what the mind refuses to process. The patterns run what the willpower cannot override. The identity performs what the deepest belief about yourself has already decided.',
        defaultValue: 'Most people who feel limited are not lacking ambition, intelligence, or effort. They are operating against an invisible internal structure — subconscious conditioning, unresolved emotional memory, and an identity that was shaped in the absence of real tools.\n\nThe body carries what the mind refuses to process. The patterns run what the willpower cannot override. The identity performs what the deepest belief about yourself has already decided.',
        page: 'home',
        section: 'why-stuck',
        label: 'Description',
        type: 'paragraph',
        fontSizeMin: 14,
        fontSizeMax: 18,
      },
      'home-stuck-pullquote': {
        id: 'home-stuck-pullquote',
        value: 'Until you make the unconscious conscious, it will direct your life and you will call it fate.',
        defaultValue: 'Until you make the unconscious conscious, it will direct your life and you will call it fate.',
        page: 'home',
        section: 'why-stuck',
        label: 'Pull Quote',
        type: 'paragraph',
        fontSizeMin: 18,
        fontSizeMax: 28,
      },
      'home-stuck-pullquote-author': {
        id: 'home-stuck-pullquote-author',
        value: 'Carl Jung',
        defaultValue: 'Carl Jung',
        page: 'home',
        section: 'why-stuck',
        label: 'Pull Quote Author',
        type: 'label',
        fontSizeMin: 12,
        fontSizeMax: 16,
      },
      'home-stuck-description-2': {
        id: 'home-stuck-description-2',
        value: 'The 4X System is the process of making that unconscious architecture visible, accessible, and changeable — at the root. Not at the symptom.',
        defaultValue: 'The 4X System is the process of making that unconscious architecture visible, accessible, and changeable — at the root. Not at the symptom.',
        page: 'home',
        section: 'why-stuck',
        label: 'Description 2',
        type: 'paragraph',
        fontSizeMin: 14,
        fontSizeMax: 18,
      },
      // Home Page - CTA
      'home-cta-section-label': {
        id: 'home-cta-section-label',
        value: 'BRAND POSITIONING',
        defaultValue: 'BRAND POSITIONING',
        page: 'home',
        section: 'cta',
        label: 'Section Label',
        type: 'label',
        fontSizeMin: 12,
        fontSizeMax: 16,
      },
      'home-cta-heading': {
        id: 'home-cta-heading',
        value: 'Ataraxia Is Not a Coaching Service. It Is a System.',
        defaultValue: 'Ataraxia Is Not a Coaching Service. It Is a System.',
        page: 'home',
        section: 'cta',
        label: 'Heading',
        type: 'heading',
        fontSizeMin: 24,
        fontSizeMax: 48,
      },
      'home-cta-description': {
        id: 'home-cta-description',
        value: 'There is a profound difference between support and transformation. Between managing your life and fundamentally redesigning it from the inside.\n\nAtaraxia operates at the level of identity — the deepest layer of the self, where all of your outcomes are already determined before a single conscious decision is made. The work here is root-cause, evidence-informed, and built for those who take themselves seriously enough to go all the way.\n\nThis is where the highest version of your life is waiting. Not as a promise. As a system.',
        defaultValue: 'There is a profound difference between support and transformation. Between managing your life and fundamentally redesigning it from the inside.\n\nAtaraxia operates at the level of identity — the deepest layer of the self, where all of your outcomes are already determined before a single conscious decision is made. The work here is root-cause, evidence-informed, and built for those who take themselves seriously enough to go all the way.\n\nThis is where the highest version of your life is waiting. Not as a promise. As a system.',
        page: 'home',
        section: 'cta',
        label: 'Description',
        type: 'paragraph',
        fontSizeMin: 14,
        fontSizeMax: 18,
      },
      'home-cta-button-1': {
        id: 'home-cta-button-1',
        value: '▶  Apply for The 4X Reset Experience',
        defaultValue: '▶  Apply for The 4X Reset Experience',
        page: 'home',
        section: 'cta',
        label: 'CTA Button 1',
        type: 'button',
        fontSizeMin: 14,
        fontSizeMax: 18,
      },
      'home-cta-button-2': {
        id: 'home-cta-button-2',
        value: '▶  Book a Private Clarity Call',
        defaultValue: '▶  Book a Private Clarity Call',
        page: 'home',
        section: 'cta',
        label: 'CTA Button 2',
        type: 'button',
        fontSizeMin: 14,
        fontSizeMax: 18,
      },
      'home-cta-button-3': {
        id: 'home-cta-button-3',
        value: '▶  Explore Journals & Tools',
        defaultValue: '▶  Explore Journals & Tools',
        page: 'home',
        section: 'cta',
        label: 'CTA Button 3',
        type: 'button',
        fontSizeMin: 14,
        fontSizeMax: 18,
      },
      // About Page
      'about-heading': {
        id: 'about-heading',
        value: 'Built From the Inside. Backed by Mastery.',
        defaultValue: 'Built From the Inside. Backed by Mastery.',
        page: 'about',
        section: 'intro',
        label: 'Heading',
        type: 'heading',
        fontSizeMin: 28,
        fontSizeMax: 72,
      },
      'about-intro-text': {
        id: 'about-intro-text',
        value: 'Before the certifications. Before the framework. Before Ataraxia.\n\nThere was a woman learning, very slowly, how to come home to herself.',
        defaultValue: 'Before the certifications. Before the framework. Before Ataraxia.\n\nThere was a woman learning, very slowly, how to come home to herself.',
        page: 'about',
        section: 'intro',
        label: 'Intro Text',
        type: 'paragraph',
        fontSizeMin: 14,
        fontSizeMax: 18,
      },
      'about-origin-section-label': {
        id: 'about-origin-section-label',
        value: "AQSA'S ORIGIN STORY",
        defaultValue: "AQSA'S ORIGIN STORY",
        page: 'about',
        section: 'origin',
        label: 'Section Label',
        type: 'label',
        fontSizeMin: 12,
        fontSizeMax: 16,
      },
      'about-origin-heading': {
        id: 'about-origin-heading',
        value: 'The Origin of Ataraxia',
        defaultValue: 'The Origin of Ataraxia',
        page: 'about',
        section: 'origin',
        label: 'Heading',
        type: 'heading',
        fontSizeMin: 24,
        fontSizeMax: 48,
      },
      'about-origin-text-1': {
        id: 'about-origin-text-1',
        value: "Aqsa Khan's path to this work did not begin with a calling. It began with survival.\n\nGrowing up through a childhood marked by pain she had no language for, she developed what so many high-functioning people develop: the ability to appear whole while quietly fragmenting inside. She was capable. She was accomplished. She was also completely disconnected from herself.\n\nFor years, she operated on autopilot — achieving externally, disappearing internally. The surface held. What was underneath did not.",
        defaultValue: "Aqsa Khan's path to this work did not begin with a calling. It began with survival.\n\nGrowing up through a childhood marked by pain she had no language for, she developed what so many high-functioning people develop: the ability to appear whole while quietly fragmenting inside. She was capable. She was accomplished. She was also completely disconnected from herself.\n\nFor years, she operated on autopilot — achieving externally, disappearing internally. The surface held. What was underneath did not.",
        page: 'about',
        section: 'origin',
        label: 'Origin Text 1',
        type: 'paragraph',
        fontSizeMin: 14,
        fontSizeMax: 18,
      },
      'about-origin-text-2': {
        id: 'about-origin-text-2',
        value: 'And then, something shifted.',
        defaultValue: 'And then, something shifted.',
        page: 'about',
        section: 'origin',
        label: 'Origin Text 2',
        type: 'heading',
        fontSizeMin: 18,
        fontSizeMax: 24,
      },
      'about-origin-text-3': {
        id: 'about-origin-text-3',
        value: "Not immediately. Not dramatically. But in the slow, unglamorous work of beginning to actually look inward, Aqsa started to connect with herself for the first time.\n\nShe began to understand her own strength — not the performance of it, but the real, embodied kind that lives beneath the need to prove. She started to see the patterns that had been running her life. She went into what was underneath: the grief she had never fully touched, the beliefs installed so early she had mistaken them for truth, the version of herself that had been waiting, quietly, for someone to come back for her.\n\nShe did the work of forgiving herself. For the years she spent not knowing. For the choices made from wounds she hadn't yet healed. For the distance she had kept from her own life.\n\nAnd in that process of releasing, rewiring, and rising — she discovered that what had transformed her was not any single tool. It was the integration of all of them. NLP for the structure of thought. Time Line Therapy™ for the emotional past. Clinical Hypnotherapy for the subconscious. Somatic work for the body's held memory. Together, they had created something she had never felt before: clarity that lived in the body, not just the mind.",
        defaultValue: "Not immediately. Not dramatically. But in the slow, unglamorous work of beginning to actually look inward, Aqsa started to connect with herself for the first time.\n\nShe began to understand her own strength — not the performance of it, but the real, embodied kind that lives beneath the need to prove. She started to see the patterns that had been running her life. She went into what was underneath: the grief she had never fully touched, the beliefs installed so early she had mistaken them for truth, the version of herself that had been waiting, quietly, for someone to come back for her.\n\nShe did the work of forgiving herself. For the years she spent not knowing. For the choices made from wounds she hadn't yet healed. For the distance she had kept from her own life.\n\nAnd in that process of releasing, rewiring, and rising — she discovered that what had transformed her was not any single tool. It was the integration of all of them. NLP for the structure of thought. Time Line Therapy™ for the emotional past. Clinical Hypnotherapy for the subconscious. Somatic work for the body's held memory. Together, they had created something she had never felt before: clarity that lived in the body, not just the mind.",
        page: 'about',
        section: 'origin',
        label: 'Origin Text 3',
        type: 'paragraph',
        fontSizeMin: 14,
        fontSizeMax: 18,
      },
      'about-pullquote': {
        id: 'about-pullquote',
        value: 'All unexpressed emotions come out in uglier forms.',
        defaultValue: 'All unexpressed emotions come out in uglier forms.',
        page: 'about',
        section: 'origin',
        label: 'Pull Quote',
        type: 'paragraph',
        fontSizeMin: 18,
        fontSizeMax: 28,
      },
      'about-pullquote-author': {
        id: 'about-pullquote-author',
        value: 'Carl Jung',
        defaultValue: 'Carl Jung',
        page: 'about',
        section: 'origin',
        label: 'Pull Quote Author',
        type: 'label',
        fontSizeMin: 12,
        fontSizeMax: 16,
      },
      'about-origin-text-4': {
        id: 'about-origin-text-4',
        value: "She had lived that truth. And she had found the path through it.\n\nAtaraxia was built from that path. Not as a brand, but as a movement — a conviction that the most profound transformation available to a human being is not the kind that improves your life. It's the kind that changes who is living it.\n\nToday, Aqsa is an internationally certified NLP Coach, Time Line Therapy™ Practitioner, and Clinical Hypnotherapist. She works with high-achieving women, executives, and leaders who sense that something far deeper is available to them — and are ready to do the real work of accessing it.",
        defaultValue: "She had lived that truth. And she had found the path through it.\n\nAtaraxia was built from that path. Not as a brand, but as a movement — a conviction that the most profound transformation available to a human being is not the kind that improves your life. It's the kind that changes who is living it.\n\nToday, Aqsa is an internationally certified NLP Coach, Time Line Therapy™ Practitioner, and Clinical Hypnotherapist. She works with high-achieving women, executives, and leaders who sense that something far deeper is available to them — and are ready to do the real work of accessing it.",
        page: 'about',
        section: 'origin',
        label: 'Origin Text 4',
        type: 'paragraph',
        fontSizeMin: 14,
        fontSizeMax: 18,
      },
      'about-credentials-section-label': {
        id: 'about-credentials-section-label',
        value: 'CREDENTIALS',
        defaultValue: 'CREDENTIALS',
        page: 'about',
        section: 'credentials',
        label: 'Section Label',
        type: 'label',
        fontSizeMin: 12,
        fontSizeMax: 16,
      },
      'about-credentials-heading': {
        id: 'about-credentials-heading',
        value: 'Certifications & Training',
        defaultValue: 'Certifications & Training',
        page: 'about',
        section: 'credentials',
        label: 'Heading',
        type: 'heading',
        fontSizeMin: 24,
        fontSizeMax: 48,
      },
      'about-credential-1': {
        id: 'about-credential-1',
        value: '· Internationally Certified NLP Coach (ABNLP)',
        defaultValue: '· Internationally Certified NLP Coach (ABNLP)',
        page: 'about',
        section: 'credentials',
        label: 'Credential 1',
        type: 'paragraph',
        fontSizeMin: 14,
        fontSizeMax: 18,
      },
      'about-credential-2': {
        id: 'about-credential-2',
        value: '· Certified Time Line Therapy™ Practitioner (TLTA)',
        defaultValue: '· Certified Time Line Therapy™ Practitioner (TLTA)',
        page: 'about',
        section: 'credentials',
        label: 'Credential 2',
        type: 'paragraph',
        fontSizeMin: 14,
        fontSizeMax: 18,
      },
      'about-credential-3': {
        id: 'about-credential-3',
        value: '· Certified Clinical Hypnotherapist',
        defaultValue: '· Certified Clinical Hypnotherapist',
        page: 'about',
        section: 'credentials',
        label: 'Credential 3',
        type: 'paragraph',
        fontSizeMin: 14,
        fontSizeMax: 18,
      },
      'about-credential-4': {
        id: 'about-credential-4',
        value: '· Specialisation in Somatic Emotional Release',
        defaultValue: '· Specialisation in Somatic Emotional Release',
        page: 'about',
        section: 'credentials',
        label: 'Credential 4',
        type: 'paragraph',
        fontSizeMin: 14,
        fontSizeMax: 18,
      },
      'about-credential-5': {
        id: 'about-credential-5',
        value: '· Mental Health Advocate & Practitioner',
        defaultValue: '· Mental Health Advocate & Practitioner',
        page: 'about',
        section: 'credentials',
        label: 'Credential 5',
        type: 'paragraph',
        fontSizeMin: 14,
        fontSizeMax: 18,
      },
      'about-cta-1': {
        id: 'about-cta-1',
        value: "▶  Read Aqsa's Full Story",
        defaultValue: "▶  Read Aqsa's Full Story",
        page: 'about',
        section: 'credentials',
        label: 'CTA Button 1',
        type: 'button',
        fontSizeMin: 14,
        fontSizeMax: 18,
      },
      'about-cta-2': {
        id: 'about-cta-2',
        value: '▶  Book a Private Clarity Call',
        defaultValue: '▶  Book a Private Clarity Call',
        page: 'about',
        section: 'credentials',
        label: 'CTA Button 2',
        type: 'button',
        fontSizeMin: 14,
        fontSizeMax: 18,
      },
      // Services Page
      'services-heading': {
        id: 'services-heading',
        value: 'The Work. For Those Who Are Ready.',
        defaultValue: 'The Work. For Those Who Are Ready.',
        page: 'services',
        section: 'intro',
        label: 'Heading',
        type: 'heading',
        fontSizeMin: 28,
        fontSizeMax: 72,
      },
      'services-intro-text': {
        id: 'services-intro-text',
        value: 'Every service within Ataraxia is designed around the 4X System — operating at the intersection of emotional release, subconscious rewiring, identity expansion, and internal alignment. Each offering addresses a different depth of access and a different stage of readiness.',
        defaultValue: 'Every service within Ataraxia is designed around the 4X System — operating at the intersection of emotional release, subconscious rewiring, identity expansion, and internal alignment. Each offering addresses a different depth of access and a different stage of readiness.',
        page: 'services',
        section: 'intro',
        label: 'Intro Text',
        type: 'paragraph',
        fontSizeMin: 14,
        fontSizeMax: 18,
      },
      'services-service1-section-label': {
        id: 'services-service1-section-label',
        value: 'SERVICE 01 — SIGNATURE OFFERING',
        defaultValue: 'SERVICE 01 — SIGNATURE OFFERING',
        page: 'services',
        section: 'service1',
        label: 'Section Label',
        type: 'label',
        fontSizeMin: 12,
        fontSizeMax: 16,
      },
      'services-service1-heading': {
        id: 'services-service1-heading',
        value: 'The 4X Reset Experience — 3-Day Intensive',
        defaultValue: 'The 4X Reset Experience — 3-Day Intensive',
        page: 'services',
        section: 'service1',
        label: 'Heading',
        type: 'heading',
        fontSizeMin: 24,
        fontSizeMax: 48,
      },
      'services-service1-subtitle': {
        id: 'services-service1-subtitle',
        value: 'The deepest access available within Ataraxia.',
        defaultValue: 'The deepest access available within Ataraxia.',
        page: 'services',
        section: 'service1',
        label: 'Subtitle',
        type: 'subheading',
        fontSizeMin: 16,
        fontSizeMax: 24,
      },
      'services-service1-text-1': {
        id: 'services-service1-text-1',
        value: 'A three-day immersive built to achieve, in seventy-two hours, the internal transformation that most people spend years approaching. This is not a retreat. It is precision work — structured, intentional, and designed to leave you fundamentally different from the person who arrived.',
        defaultValue: 'A three-day immersive built to achieve, in seventy-two hours, the internal transformation that most people spend years approaching. This is not a retreat. It is precision work — structured, intentional, and designed to leave you fundamentally different from the person who arrived.',
        page: 'services',
        section: 'service1',
        label: 'Service 1 Text 1',
        type: 'paragraph',
        fontSizeMin: 14,
        fontSizeMax: 18,
      },
      'services-service1-day1': {
        id: 'services-service1-day1',
        value: 'Day 1: Release — Locate and neutralise the emotional charge at the origin. Using Time Line Therapy™ and somatic-based techniques, we dissolve the root — not the story around it, the charge beneath it.',
        defaultValue: 'Day 1: Release — Locate and neutralise the emotional charge at the origin. Using Time Line Therapy™ and somatic-based techniques, we dissolve the root — not the story around it, the charge beneath it.',
        page: 'services',
        section: 'service1',
        label: 'Day 1',
        type: 'paragraph',
        fontSizeMin: 14,
        fontSizeMax: 18,
      },
      'services-service1-day2': {
        id: 'services-service1-day2',
        value: 'Day 2: Rewire — Install the subconscious architecture of your next identity. NLP and clinical hypnotherapy work at the level below conscious thought, replacing patterns that were never chosen with ones that are.',
        defaultValue: 'Day 2: Rewire — Install the subconscious architecture of your next identity. NLP and clinical hypnotherapy work at the level below conscious thought, replacing patterns that were never chosen with ones that are.',
        page: 'services',
        section: 'service1',
        label: 'Day 2',
        type: 'paragraph',
        fontSizeMin: 14,
        fontSizeMax: 18,
      },
      'services-service1-day3': {
        id: 'services-service1-day3',
        value: 'Day 3: Rise — Embody the shift. Anchor it. Move forward as the identity you\'ve built — not as a hope, but as a lived reality.',
        defaultValue: 'Day 3: Rise — Embody the shift. Anchor it. Move forward as the identity you\'ve built — not as a hope, but as a lived reality.',
        page: 'services',
        section: 'service1',
        label: 'Day 3',
        type: 'paragraph',
        fontSizeMin: 14,
        fontSizeMax: 18,
      },
      'services-service1-text-2': {
        id: 'services-service1-text-2',
        value: 'Three tiers. One transformation.',
        defaultValue: 'Three tiers. One transformation.',
        page: 'services',
        section: 'service1',
        label: 'Service 1 Text 2',
        type: 'paragraph',
        fontSizeMin: 14,
        fontSizeMax: 18,
      },
      'services-service1-tiers': {
        id: 'services-service1-tiers',
        value: '· Access — The complete 3-day experience\n· Deep Work — Extended integration and personalised daily sessions\n· Inner Circle — Includes a private session with Aqsa',
        defaultValue: '· Access — The complete 3-day experience\n· Deep Work — Extended integration and personalised daily sessions\n· Inner Circle — Includes a private session with Aqsa',
        page: 'services',
        section: 'service1',
        label: 'Tiers',
        type: 'paragraph',
        fontSizeMin: 14,
        fontSizeMax: 18,
      },
      'services-service1-cta': {
        id: 'services-service1-cta',
        value: '▶  Apply for The 4X Reset',
        defaultValue: '▶  Apply for The 4X Reset',
        page: 'services',
        section: 'service1',
        label: 'CTA',
        type: 'button',
        fontSizeMin: 14,
        fontSizeMax: 18,
      },
      'services-service2-section-label': {
        id: 'services-service2-section-label',
        value: 'SERVICE 02 — 1:1 PREMIUM',
        defaultValue: 'SERVICE 02 — 1:1 PREMIUM',
        page: 'services',
        section: 'service2',
        label: 'Section Label',
        type: 'label',
        fontSizeMin: 12,
        fontSizeMax: 16,
      },
      'services-service2-heading': {
        id: 'services-service2-heading',
        value: 'Private Clarity & Transformation Sessions',
        defaultValue: 'Private Clarity & Transformation Sessions',
        page: 'services',
        section: 'service2',
        label: 'Heading',
        type: 'heading',
        fontSizeMin: 24,
        fontSizeMax: 48,
      },
      'services-service2-text-1': {
        id: 'services-service2-text-1',
        value: 'For those who require deep, sustained private work. Available as a 3-month or 5-month container, this is not a weekly check-in. It is a complete internal overhaul — addressing the full spectrum of what is keeping you from operating at the level you know you\'re capable of.',
        defaultValue: 'For those who require deep, sustained private work. Available as a 3-month or 5-month container, this is not a weekly check-in. It is a complete internal overhaul — addressing the full spectrum of what is keeping you from operating at the level you know you\'re capable of.',
        page: 'services',
        section: 'service2',
        label: 'Service 2 Text 1',
        type: 'paragraph',
        fontSizeMin: 14,
        fontSizeMax: 18,
      },
      'services-service2-bullets': {
        id: 'services-service2-bullets',
        value: '· Somatic-based emotional release\n· NLP subconscious reprogramming\n· Time Line Therapy™ for past emotional clearing\n· WhatsApp accountability between sessions',
        defaultValue: '· Somatic-based emotional release\n· NLP subconscious reprogramming\n· Time Line Therapy™ for past emotional clearing\n· WhatsApp accountability between sessions',
        page: 'services',
        section: 'service2',
        label: 'Bullets',
        type: 'paragraph',
        fontSizeMin: 14,
        fontSizeMax: 18,
      },
      'services-service2-cta': {
        id: 'services-service2-cta',
        value: '▶  Book a Private Discovery Call',
        defaultValue: '▶  Book a Private Discovery Call',
        page: 'services',
        section: 'service2',
        label: 'CTA',
        type: 'button',
        fontSizeMin: 14,
        fontSizeMax: 18,
      },
      'services-service3-section-label': {
        id: 'services-service3-section-label',
        value: 'SERVICE 03 — EMERGENCY SUPPORT',
        defaultValue: 'SERVICE 03 — EMERGENCY SUPPORT',
        page: 'services',
        section: 'service3',
        label: 'Section Label',
        type: 'label',
        fontSizeMin: 12,
        fontSizeMax: 16,
      },
      'services-service3-heading': {
        id: 'services-service3-heading',
        value: 'Emergency & High-Stress Sessions',
        defaultValue: 'Emergency & High-Stress Sessions',
        page: 'services',
        section: 'service3',
        label: 'Heading',
        type: 'heading',
        fontSizeMin: 24,
        fontSizeMax: 48,
      },
      'services-service3-badge': {
        id: 'services-service3-badge',
        value: 'DEDICATED CRISIS SUPPORT',
        defaultValue: 'DEDICATED CRISIS SUPPORT',
        page: 'services',
        section: 'service3',
        label: 'Badge',
        type: 'label',
        fontSizeMin: 14,
        fontSizeMax: 18,
      },
      'services-service3-text-1': {
        id: 'services-service3-text-1',
        value: 'When life doesn\'t wait, you won\'t be alone in it.\n\nA dedicated, trained professional is assigned to you — available for acute emotional processing, grounding, nervous system regulation, and focused subconscious intervention when the pressure is highest. This is not a chatbot, a helpline, or a waiting list. It is a human, trained specifically in the Ataraxia methodology, present for you in real time.',
        defaultValue: 'When life doesn\'t wait, you won\'t be alone in it.\n\nA dedicated, trained professional is assigned to you — available for acute emotional processing, grounding, nervous system regulation, and focused subconscious intervention when the pressure is highest. This is not a chatbot, a helpline, or a waiting list. It is a human, trained specifically in the Ataraxia methodology, present for you in real time.',
        page: 'services',
        section: 'service3',
        label: 'Service 3 Text 1',
        type: 'paragraph',
        fontSizeMin: 14,
        fontSizeMax: 18,
      },
      'services-service3-bullets': {
        id: 'services-service3-bullets',
        value: '▶  WhatsApp accountability between sessions\n▶  Available to existing Ataraxia clients and selected new applicants\n▶  Sessions available remotely, across time zones',
        defaultValue: '▶  WhatsApp accountability between sessions\n▶  Available to existing Ataraxia clients and selected new applicants\n▶  Sessions available remotely, across time zones',
        page: 'services',
        section: 'service3',
        label: 'Bullets',
        type: 'paragraph',
        fontSizeMin: 14,
        fontSizeMax: 18,
      },
      'services-service3-cta': {
        id: 'services-service3-cta',
        value: '▶  Enquire About Crisis Support',
        defaultValue: '▶  Enquire About Crisis Support',
        page: 'services',
        section: 'service3',
        label: 'CTA',
        type: 'button',
        fontSizeMin: 14,
        fontSizeMax: 18,
      },
      'services-service4-section-label': {
        id: 'services-service4-section-label',
        value: 'SERVICE 04 — GROUP & COLLECTIVE',
        defaultValue: 'SERVICE 04 — GROUP & COLLECTIVE',
        page: 'services',
        section: 'service4',
        label: 'Section Label',
        type: 'label',
        fontSizeMin: 12,
        fontSizeMax: 16,
      },
      'services-service4-heading': {
        id: 'services-service4-heading',
        value: 'Group Experiences & Themed Workshops',
        defaultValue: 'Group Experiences & Themed Workshops',
        page: 'services',
        section: 'service4',
        label: 'Heading',
        type: 'heading',
        fontSizeMin: 24,
        fontSizeMax: 48,
      },
      'services-service4-text-1': {
        id: 'services-service4-text-1',
        value: 'Collective transformation carries its own intelligence. Ataraxia\'s group experiences are intimate, facilitated, and designed to create the conditions for genuine emotional release and identity shift within a shared container.',
        defaultValue: 'Collective transformation carries its own intelligence. Ataraxia\'s group experiences are intimate, facilitated, and designed to create the conditions for genuine emotional release and identity shift within a shared container.',
        page: 'services',
        section: 'service4',
        label: 'Service 4 Text 1',
        type: 'paragraph',
        fontSizeMin: 14,
        fontSizeMax: 18,
      },
      'services-service4-bullets': {
        id: 'services-service4-bullets',
        value: '· Monthly emotional release circles\n· Belief rewiring workshops\n· Identity shift intensives\n· Curated collaborative events with partner practitioners — yoga, arts, exclusive Islamabad experiences',
        defaultValue: '· Monthly emotional release circles\n· Belief rewiring workshops\n· Identity shift intensives\n· Curated collaborative events with partner practitioners — yoga, arts, exclusive Islamabad experiences',
        page: 'services',
        section: 'service4',
        label: 'Bullets',
        type: 'paragraph',
        fontSizeMin: 14,
        fontSizeMax: 18,
      },
      'services-service4-cta': {
        id: 'services-service4-cta',
        value: '▶  Join the Next Group Session',
        defaultValue: '▶  Join the Next Group Session',
        page: 'services',
        section: 'service4',
        label: 'CTA',
        type: 'button',
        fontSizeMin: 14,
        fontSizeMax: 18,
      },
      'services-service5-section-label': {
        id: 'services-service5-section-label',
        value: 'SERVICE 05 — CORPORATE',
        defaultValue: 'SERVICE 05 — CORPORATE',
        page: 'services',
        section: 'service5',
        label: 'Section Label',
        type: 'label',
        fontSizeMin: 12,
        fontSizeMax: 16,
      },
      'services-service5-heading': {
        id: 'services-service5-heading',
        value: 'Corporate & Organisational Training',
        defaultValue: 'Corporate & Organisational Training',
        page: 'services',
        section: 'service5',
        label: 'Heading',
        type: 'heading',
        fontSizeMin: 24,
        fontSizeMax: 48,
      },
      'services-service5-text-1': {
        id: 'services-service5-text-1',
        value: 'Performance at the highest level is not a skills problem. It is an inner architecture problem. Ataraxia\'s corporate training addresses the invisible layer beneath team performance: the emotional intelligence, communication patterns, and subconscious dynamics that shape every outcome.',
        defaultValue: 'Performance at the highest level is not a skills problem. It is an inner architecture problem. Ataraxia\'s corporate training addresses the invisible layer beneath team performance: the emotional intelligence, communication patterns, and subconscious dynamics that shape every outcome.',
        page: 'services',
        section: 'service5',
        label: 'Service 5 Text 1',
        type: 'paragraph',
        fontSizeMin: 14,
        fontSizeMax: 18,
      },
      'services-service5-bullets': {
        id: 'services-service5-bullets',
        value: '· Emotional intelligence for leadership\n· Communication patterns and team dynamics\n· Resilience and stress regulation under pressure\n· Mindset performance for high-stakes environments',
        defaultValue: '· Emotional intelligence for leadership\n· Communication patterns and team dynamics\n· Resilience and stress regulation under pressure\n· Mindset performance for high-stakes environments',
        page: 'services',
        section: 'service5',
        label: 'Bullets',
        type: 'paragraph',
        fontSizeMin: 14,
        fontSizeMax: 18,
      },
      'services-service5-cta': {
        id: 'services-service5-cta',
        value: '▶  Enquire About Corporate Training',
        defaultValue: '▶  Enquire About Corporate Training',
        page: 'services',
        section: 'service5',
        label: 'CTA',
        type: 'button',
        fontSizeMin: 14,
        fontSizeMax: 18,
      },
      // Contact Page
      'contact-heading': {
        id: 'contact-heading',
        value: 'Let\'s Begin Your Rise.',
        defaultValue: 'Let\'s Begin Your Rise.',
        page: 'contact',
        section: 'intro',
        label: 'Heading',
        type: 'heading',
        fontSizeMin: 28,
        fontSizeMax: 72,
      },
      'contact-intro-text': {
        id: 'contact-intro-text',
        value: 'Every significant transformation begins with a single, intentional decision. This is yours.\n\nAtaraxia accepts a limited number of new clients each month — not as a tactic, but because the depth of this work requires full presence and precision. Each person who enters this space receives exactly that.\n\nIf something in you already knows — trust it.',
        defaultValue: 'Every significant transformation begins with a single, intentional decision. This is yours.\n\nAtaraxia accepts a limited number of new clients each month — not as a tactic, but because the depth of this work requires full presence and precision. Each person who enters this space receives exactly that.\n\nIf something in you already knows — trust it.',
        page: 'contact',
        section: 'intro',
        label: 'Intro Text',
        type: 'paragraph',
        fontSizeMin: 14,
        fontSizeMax: 18,
      },
      'contact-how-to-begin-label': {
        id: 'contact-how-to-begin-label',
        value: 'HOW TO BEGIN',
        defaultValue: 'HOW TO BEGIN',
        page: 'contact',
        section: 'how-to-begin',
        label: 'Section Label',
        type: 'label',
        fontSizeMin: 12,
        fontSizeMax: 16,
      },
      'contact-card1-number': {
        id: 'contact-card1-number',
        value: '01',
        defaultValue: '01',
        page: 'contact',
        section: 'how-to-begin',
        label: 'Card 1 Number',
        type: 'label',
        fontSizeMin: 14,
        fontSizeMax: 18,
      },
      'contact-card1-title': {
        id: 'contact-card1-title',
        value: 'Book a Free Discovery Call',
        defaultValue: 'Book a Free Discovery Call',
        page: 'contact',
        section: 'how-to-begin',
        label: 'Card 1 Title',
        type: 'heading',
        fontSizeMin: 18,
        fontSizeMax: 24,
      },
      'contact-card1-text': {
        id: 'contact-card1-text',
        value: '30 minutes to understand where you are and what is possible',
        defaultValue: '30 minutes to understand where you are and what is possible',
        page: 'contact',
        section: 'how-to-begin',
        label: 'Card 1 Text',
        type: 'paragraph',
        fontSizeMin: 14,
        fontSizeMax: 18,
      },
      'contact-card2-number': {
        id: 'contact-card2-number',
        value: '02',
        defaultValue: '02',
        page: 'contact',
        section: 'how-to-begin',
        label: 'Card 2 Number',
        type: 'label',
        fontSizeMin: 14,
        fontSizeMax: 18,
      },
      'contact-card2-title': {
        id: 'contact-card2-title',
        value: 'Apply for the 4X Reset Experience',
        defaultValue: 'Apply for the 4X Reset Experience',
        page: 'contact',
        section: 'how-to-begin',
        label: 'Card 2 Title',
        type: 'heading',
        fontSizeMin: 18,
        fontSizeMax: 24,
      },
      'contact-card2-text': {
        id: 'contact-card2-text',
        value: 'By application only, limited intake',
        defaultValue: 'By application only, limited intake',
        page: 'contact',
        section: 'how-to-begin',
        label: 'Card 2 Text',
        type: 'paragraph',
        fontSizeMin: 14,
        fontSizeMax: 18,
      },
      'contact-card3-number': {
        id: 'contact-card3-number',
        value: '03',
        defaultValue: '03',
        page: 'contact',
        section: 'how-to-begin',
        label: 'Card 3 Number',
        type: 'label',
        fontSizeMin: 14,
        fontSizeMax: 18,
      },
      'contact-card3-title': {
        id: 'contact-card3-title',
        value: 'Corporate Enquiries',
        defaultValue: 'Corporate Enquiries',
        page: 'contact',
        section: 'how-to-begin',
        label: 'Card 3 Title',
        type: 'heading',
        fontSizeMin: 18,
        fontSizeMax: 24,
      },
      'contact-card3-text': {
        id: 'contact-card3-text',
        value: 'For team and organisational training',
        defaultValue: 'For team and organisational training',
        page: 'contact',
        section: 'how-to-begin',
        label: 'Card 3 Text',
        type: 'paragraph',
        fontSizeMin: 14,
        fontSizeMax: 18,
      },
      'contact-cta-1': {
        id: 'contact-cta-1',
        value: '▶  Book Your Free Discovery Call',
        defaultValue: '▶  Book Your Free Discovery Call',
        page: 'contact',
        section: 'how-to-begin',
        label: 'CTA Button 1',
        type: 'button',
        fontSizeMin: 14,
        fontSizeMax: 18,
      },
      'contact-cta-2': {
        id: 'contact-cta-2',
        value: '▶  Submit an Application',
        defaultValue: '▶  Submit an Application',
        page: 'contact',
        section: 'how-to-begin',
        label: 'CTA Button 2',
        type: 'button',
        fontSizeMin: 14,
        fontSizeMax: 18,
      },
      'contact-footer-text-1': {
        id: 'contact-footer-text-1',
        value: 'WhatsApp enquiries welcome. Response within 24 hours.',
        defaultValue: 'WhatsApp enquiries welcome. Response within 24 hours.',
        page: 'contact',
        section: 'footer',
        label: 'Footer Text 1',
        type: 'paragraph',
        fontSizeMin: 12,
        fontSizeMax: 16,
      },
      'contact-footer-text-2': {
        id: 'contact-footer-text-2',
        value: 'Email Aqsa:',
        defaultValue: 'Email Aqsa:',
        page: 'contact',
        section: 'footer',
        label: 'Footer Text 2',
        type: 'paragraph',
        fontSizeMin: 12,
        fontSizeMax: 16,
      },
      'contact-email': {
        id: 'contact-email',
        value: 'aqsakhan.growth@gmail.com',
        defaultValue: 'aqsakhan.growth@gmail.com',
        page: 'contact',
        section: 'footer',
        label: 'Email',
        type: 'link',
        fontSizeMin: 12,
        fontSizeMax: 16,
      },
    },
    images: {
      'navbar-logo': {
        id: 'navbar-logo',
        src: '/favicon.svg',
        defaultSrc: '/favicon.svg',
        alt: 'Ataraxia Logo',
        page: 'shared',
        section: 'navbar',
        label: 'Logo',
      },
      'home-hero-bg': {
        id: 'home-hero-bg',
        src: '/images/img_hero_woman_light.png',
        defaultSrc: '/images/img_hero_woman_light.png',
        alt: 'A woman walks toward a golden light through storm clouds — Ataraxia',
        page: 'home',
        section: 'hero',
        label: 'Hero Background',
      },
      'home-4x-framework': {
        id: 'home-4x-framework',
        src: '/images/ataraxia_4x_cycle_framework.svg',
        defaultSrc: '/images/ataraxia_4x_cycle_framework.svg',
        alt: 'The Ataraxia 4X Transformation Cycle — Release, Rewire, Rise, Live 4X',
        page: 'home',
        section: '4x-framework',
        label: '4X Framework Diagram',
      },
      'home-layers-depth': {
        id: 'home-layers-depth',
        src: '/images/ataraxia_layers_depth.svg',
        defaultSrc: '/images/ataraxia_layers_depth.svg',
        alt: 'The invisible layers of the subconscious — the architecture Ataraxia works at',
        page: 'home',
        section: 'why-stuck',
        label: 'Layers Depth Diagram',
      },
      'about-journey-path': {
        id: 'about-journey-path',
        src: '/images/ataraxia_journey_path.svg',
        defaultSrc: '/images/ataraxia_journey_path.svg',
        alt: 'The path of transformation — Ataraxia by Aqsa Khan',
        page: 'about',
        section: 'intro',
        label: 'Journey Path Image',
      },
      'about-group-session': {
        id: 'about-group-session',
        src: '/images/img_group_session.png',
        defaultSrc: '/images/img_group_session.png',
        alt: 'Aqsa Khan facilitating an Ataraxia group transformation session',
        page: 'about',
        section: 'origin',
        label: 'Group Session Image',
      },
      'services-triad-integration': {
        id: 'services-triad-integration',
        src: '/images/ataraxia_triad_integration.svg',
        defaultSrc: '/images/ataraxia_triad_integration.svg',
        alt: 'The Ataraxia triad: Emotional Release, Subconscious Rewiring, Identity Integration',
        page: 'services',
        section: 'intro',
        label: 'Triad Integration Diagram',
      },
      'services-5-modalities': {
        id: 'services-5-modalities',
        src: '/images/img_5_modalities.png',
        defaultSrc: '/images/img_5_modalities.png',
        alt: 'The five transformation modalities used in the Ataraxia 4X Reset',
        page: 'services',
        section: 'service1',
        label: '5 Modalities Image',
      },
      'services-energy-frequency': {
        id: 'services-energy-frequency',
        src: '/images/ataraxia_energy_frequency.svg',
        defaultSrc: '/images/ataraxia_energy_frequency.svg',
        alt: 'Energy and frequency alignment — Ataraxia group transformation',
        page: 'services',
        section: 'service4',
        label: 'Energy Frequency Diagram',
      },
    },
    sections: {
      // Home
      'home-hero': {
        id: 'home-hero',
        page: 'home',
        label: 'Hero Section',
        order: 1,
        visible: true,
        bgColor: '#0A0A0A',
        paddingTop: 80,
        paddingBottom: 80,
        isDeletable: false,
      },
      'home-4x-framework': {
        id: 'home-4x-framework',
        page: 'home',
        label: '4X Framework',
        order: 2,
        visible: true,
        bgColor: '#0A0A0A',
        paddingTop: 60,
        paddingBottom: 60,
        isDeletable: false,
      },
      'home-why-stuck': {
        id: 'home-why-stuck',
        page: 'home',
        label: 'Why People Stay Stuck',
        order: 3,
        visible: true,
        bgColor: '#0A0A0A',
        paddingTop: 60,
        paddingBottom: 60,
        isDeletable: false,
      },
      'home-cta': {
        id: 'home-cta',
        page: 'home',
        label: 'Final CTA',
        order: 4,
        visible: true,
        bgColor: '#0A0A0A',
        paddingTop: 60,
        paddingBottom: 60,
        isDeletable: false,
      },

      // About
      'about-intro': {
        id: 'about-intro',
        page: 'about',
        label: 'Introduction',
        order: 1,
        visible: true,
        bgColor: '#0A0A0A',
        paddingTop: 80,
        paddingBottom: 60,
        isDeletable: false,
      },
      'about-origin': {
        id: 'about-origin',
        page: 'about',
        label: 'Origin Story',
        order: 2,
        visible: true,
        bgColor: '#0A0A0A',
        paddingTop: 60,
        paddingBottom: 60,
        isDeletable: false,
      },
      'about-credentials': {
        id: 'about-credentials',
        page: 'about',
        label: 'Credentials',
        order: 3,
        visible: true,
        bgColor: '#0A0A0A',
        paddingTop: 60,
        paddingBottom: 80,
        isDeletable: false,
      },

      // Services
      'services-intro': {
        id: 'services-intro',
        page: 'services',
        label: 'Introduction',
        order: 1,
        visible: true,
        bgColor: '#0A0A0A',
        paddingTop: 80,
        paddingBottom: 60,
        isDeletable: false,
      },
      'services-service1': {
        id: 'services-service1',
        page: 'services',
        label: '4X Reset Experience',
        order: 2,
        visible: true,
        bgColor: '#0A0A0A',
        paddingTop: 60,
        paddingBottom: 60,
        isDeletable: false,
      },
      'services-service2': {
        id: 'services-service2',
        page: 'services',
        label: 'Private Sessions',
        order: 3,
        visible: true,
        bgColor: '#0A0A0A',
        paddingTop: 60,
        paddingBottom: 60,
        isDeletable: false,
      },
      'services-service3': {
        id: 'services-service3',
        page: 'services',
        label: 'Emergency Support',
        order: 4,
        visible: true,
        bgColor: '#0A0A0A',
        paddingTop: 60,
        paddingBottom: 60,
        isDeletable: false,
      },
      'services-service4': {
        id: 'services-service4',
        page: 'services',
        label: 'Group Work',
        order: 5,
        visible: true,
        bgColor: '#0A0A0A',
        paddingTop: 60,
        paddingBottom: 60,
        isDeletable: false,
      },
      'services-service5': {
        id: 'services-service5',
        page: 'services',
        label: 'Corporate Training',
        order: 6,
        visible: true,
        bgColor: '#0A0A0A',
        paddingTop: 60,
        paddingBottom: 80,
        isDeletable: false,
      },

      // Contact
      'contact-intro': {
        id: 'contact-intro',
        page: 'contact',
        label: 'Introduction',
        order: 1,
        visible: true,
        bgColor: '#0A0A0A',
        paddingTop: 80,
        paddingBottom: 60,
        isDeletable: false,
      },
      'contact-how-to-begin': {
        id: 'contact-how-to-begin',
        page: 'contact',
        label: 'How To Begin',
        order: 2,
        visible: true,
        bgColor: '#0A0A0A',
        paddingTop: 60,
        paddingBottom: 80,
        isDeletable: false,
      },

      // Workshops
      'workshops-intro': {
        id: 'workshops-intro',
        page: 'workshops',
        label: 'Introduction',
        order: 1,
        visible: true,
        bgColor: '#0A0A0A',
        paddingTop: 80,
        paddingBottom: 80,
        isDeletable: false,
      },

      // Journals
      'journals-intro': {
        id: 'journals-intro',
        page: 'journals',
        label: 'Introduction',
        order: 1,
        visible: true,
        bgColor: '#0A0A0A',
        paddingTop: 80,
        paddingBottom: 80,
        isDeletable: false,
      },

      // Blog
      'blog-intro': {
        id: 'blog-intro',
        page: 'blog',
        label: 'Introduction',
        order: 1,
        visible: true,
        bgColor: '#0A0A0A',
        paddingTop: 80,
        paddingBottom: 80,
        isDeletable: false,
      },

      // Book Call
      'book-call-intro': {
        id: 'book-call-intro',
        page: 'book-call',
        label: 'Introduction',
        order: 1,
        visible: true,
        bgColor: '#0A0A0A',
        paddingTop: 80,
        paddingBottom: 80,
        isDeletable: false,
      },

      // Apply
      'application-intro': {
        id: 'application-intro',
        page: 'apply',
        label: 'Introduction',
        order: 1,
        visible: true,
        bgColor: '#0A0A0A',
        paddingTop: 80,
        paddingBottom: 80,
        isDeletable: false,
      },

      // Privacy Policy
      'privacy-policy-intro': {
        id: 'privacy-policy-intro',
        page: 'privacy-policy',
        label: 'Introduction',
        order: 1,
        visible: true,
        bgColor: '#0A0A0A',
        paddingTop: 80,
        paddingBottom: 80,
        isDeletable: false,
      },

      // Terms of Use
      'terms-of-use-intro': {
        id: 'terms-of-use-intro',
        page: 'terms-of-use',
        label: 'Introduction',
        order: 1,
        visible: true,
        bgColor: '#0A0A0A',
        paddingTop: 80,
        paddingBottom: 80,
        isDeletable: false,
      },

      // Navbar
      'navbar-logo': {
        id: 'navbar-logo',
        page: 'shared',
        label: 'Logo area',
        order: 1,
        visible: true,
        bgColor: '#0A0A0A',
        paddingTop: 16,
        paddingBottom: 16,
        isDeletable: false,
      },
      'navbar-links': {
        id: 'navbar-links',
        page: 'shared',
        label: 'Navigation links',
        order: 2,
        visible: true,
        bgColor: '#0A0A0A',
        paddingTop: 16,
        paddingBottom: 16,
        isDeletable: false,
      },
      'navbar-cta': {
        id: 'navbar-cta',
        page: 'shared',
        label: 'CTA button',
        order: 3,
        visible: true,
        bgColor: '#0A0A0A',
        paddingTop: 16,
        paddingBottom: 16,
        isDeletable: false,
      },
      'navbar-mobile': {
        id: 'navbar-mobile',
        page: 'shared',
        label: 'Mobile menu',
        order: 4,
        visible: true,
        bgColor: '#0A0A0A',
        paddingTop: 16,
        paddingBottom: 16,
        isDeletable: false,
      },

      // Footer
      'footer-brand': {
        id: 'footer-brand',
        page: 'shared',
        label: 'Footer logo/brand',
        order: 1,
        visible: true,
        bgColor: '#0A0A0A',
        paddingTop: 32,
        paddingBottom: 16,
        isDeletable: false,
      },
      'footer-links1': {
        id: 'footer-links1',
        page: 'shared',
        label: 'Footer links column 1',
        order: 2,
        visible: true,
        bgColor: '#0A0A0A',
        paddingTop: 16,
        paddingBottom: 16,
        isDeletable: false,
      },
      'footer-links2': {
        id: 'footer-links2',
        page: 'shared',
        label: 'Footer links column 2',
        order: 3,
        visible: true,
        bgColor: '#0A0A0A',
        paddingTop: 16,
        paddingBottom: 16,
        isDeletable: false,
      },
      'footer-social': {
        id: 'footer-social',
        page: 'shared',
        label: 'Social media links',
        order: 4,
        visible: true,
        bgColor: '#0A0A0A',
        paddingTop: 16,
        paddingBottom: 16,
        isDeletable: false,
      },
      'footer-copyright': {
        id: 'footer-copyright',
        page: 'shared',
        label: 'Copyright text',
        order: 5,
        visible: true,
        bgColor: '#0A0A0A',
        paddingTop: 16,
        paddingBottom: 32,
        isDeletable: false,
      },
    },
    theme: {
      activePreset: 'default',
      backgroundColor: '#0A0A0A',
      textPrimary: '#F5F0E8',
      textSecondary: '#A09880',
      accentColor: '#B8962E',
      cardBackground: '#0A0A0A',
      cardBorder: '#2A2A2A',
      buttonBackground: '#B8962E',
      buttonText: '#0A0A0A',
      borderRadius: 8,
      spacing: 'normal',
      containerWidth: 1280,
    },
    typography: {
      headingFont: 'Palatino Linotype, serif',
      bodyFont: 'Inter, sans-serif',
      uiFont: 'Inter, sans-serif',
      fontSizes: {
        xs: 12,
        sm: 14,
        base: 16,
        lg: 18,
        xl: 20,
        '2xl': 24,
        '3xl': 30,
        '4xl': 36,
        '5xl': 48,
      },
      fontWeights: {
        normal: 400,
        medium: 500,
        semibold: 600,
        bold: 700,
      },
      lineHeight: 1.8,
      letterSpacing: 0.5,
      alignments: {
        hero: 'left',
        body: 'left',
      },
    },
    lastSaved: null,
  };
}
